-- BloomOS Ring 4: stored executive briefings (modules/01-command-center.md).
-- Generated by lib/briefing.ts: numbers are computed by SQL, the model only
-- narrates them. Read = reports.read (board_viewer included); write happens
-- in server paths (service role) — org.manage for any client-side edits.

create table if not exists briefings (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references orgs(id),
  kind text not null default 'weekly' check (kind in ('weekly','on_demand')),
  headline text,
  narrative text,
  priorities jsonb not null default '[]',
  data jsonb not null default '{}',
  model text,
  created_at timestamptz not null default now()
);
create index if not exists briefings_org_created_idx on briefings (org_id, created_at desc);

do $$
declare
  aa uuid;
  t text := 'briefings';
begin
  select id into aa from orgs where slug = 'ambition-angels';
  if aa is null then
    raise exception 'ambition-angels org not found — run create_bloomos_core first';
  end if;
  execute format('alter table %I alter column org_id set default %L', t, aa);
  execute format('alter table public.%I enable row level security', t);
  execute format('drop policy if exists %I on public.%I', 'members read ' || t, t);
  execute format($p$
    create policy %I on public.%I
      for select to authenticated
      using ( (select private.has_permission(org_id, 'reports.read')) )
    $p$, 'members read ' || t, t);
  execute format('drop policy if exists %I on public.%I', 'managers write ' || t, t);
  execute format($p$
    create policy %I on public.%I
      for all to authenticated
      using ( (select private.has_permission(org_id, 'org.manage')) )
      with check ( (select private.has_permission(org_id, 'org.manage')) )
    $p$, 'managers write ' || t, t);
end $$;
