-- Seed: 2026 emerging + prospective partners (from Top Donors & Partners workbook).
-- Idempotent via (external_source, external_id). Emerging→outreach, Prospective→prospect.
insert into partners (name, kind, status, city, region, domain, external_source, external_id) values
  ('Aim High','nonprofit','outreach','San Francisco','CA','aimhigh.org','partner_import_2026','aim-high'),
  ('Alameda Unified','school','outreach','Alameda','CA',null,'partner_import_2026','alameda-unified'),
  ('BGCP','nonprofit','outreach','EPA','CA',null,'partner_import_2026','bgcp'),
  ('Breakthrough','nonprofit','outreach','San Jose','CA','breakthroughsv.org','partner_import_2026','breakthrough'),
  ('CASA','nonprofit','outreach','Redwood City','CA',null,'partner_import_2026','casa'),
  ('Castlemont High School','school','outreach','Oakland','CA',null,'partner_import_2026','castlemont-high-school'),
  ('Caterpillar Ministries (NC)','nonprofit','outreach','Huntsville','NC',null,'partner_import_2026','caterpillar-ministries-nc'),
  ('CollegeTrack','nonprofit','outreach','Oakland','CA',null,'partner_import_2026','collegetrack'),
  ('Digital Nest','nonprofit','outreach','Watsonville','CA',null,'partner_import_2026','digital-nest'),
  ('East Palo Alto Academy','school','outreach','EPA','CA',null,'partner_import_2026','east-palo-alto-academy'),
  ('Eastside College Prep','school','outreach','EPA','CA',null,'partner_import_2026','eastside-college-prep'),
  ('Enterprise for Youth','nonprofit','outreach','San Francisco','CA',null,'partner_import_2026','enterprise-for-youth'),
  ('EOYDC','nonprofit','outreach','Oakland','CA',null,'partner_import_2026','eoydc'),
  ('Ever Forward Club','nonprofit','outreach','Oakland','CA',null,'partner_import_2026','ever-forward-club'),
  ('FLY','nonprofit','outreach','Milpitas',null,null,'partner_import_2026','fly'),
  ('Friends of the Children','nonprofit','outreach','Portland','OR',null,'partner_import_2026','friends-of-the-children'),
  ('Hack The Hood','nonprofit','outreach','Oakland','CA',null,'partner_import_2026','hack-the-hood'),
  ('Hayward Unified','school','outreach','Hayward','CA',null,'partner_import_2026','hayward-unified'),
  ('Hidden Genius','nonprofit','outreach','Oakland','CA',null,'partner_import_2026','hidden-genius'),
  ('iFoster','nonprofit','outreach','Truckee','CA',null,'partner_import_2026','ifoster'),
  ('Improve Your Tomorrow','nonprofit','outreach','Sacramento','CA',null,'partner_import_2026','improve-your-tomorrow'),
  ('Just Keep Livin','nonprofit','outreach','Sherman Oaks','CA',null,'partner_import_2026','just-keep-livin'),
  ('Juvenile Hall','nonprofit','outreach','San Mateo','CA',null,'partner_import_2026','juvenile-hall'),
  ('Kingmakers','nonprofit','outreach','Oakland','CA',null,'partner_import_2026','kingmakers'),
  ('LEMO','nonprofit','outreach','Redwood City','CA',null,'partner_import_2026','lemo'),
  ('Live in Peace','nonprofit','outreach','EPA','CA',null,'partner_import_2026','live-in-peace'),
  ('MAM, Houston','nonprofit','outreach','Houston','TX',null,'partner_import_2026','mam-houston'),
  ('OneGoal','nonprofit','outreach','Oakland','CA',null,'partner_import_2026','onegoal'),
  ('Peer Heatlh Exchange','nonprofit','outreach','Washington','D.C.',null,'partner_import_2026','peer-heatlh-exchange'),
  ('Peninsula Bridge','nonprofit','outreach','San Mateo','CA',null,'partner_import_2026','peninsula-bridge'),
  ('Pivotalnow','nonprofit','outreach','San Jose','CA',null,'partner_import_2026','pivotalnow'),
  ('Redwood City High School','school','outreach','Redwood City','CA',null,'partner_import_2026','redwood-city-high-school'),
  ('RJOY','nonprofit','outreach','Oakland','CA',null,'partner_import_2026','rjoy'),
  ('Students Rising Above','nonprofit','outreach','San Francisco','CA',null,'partner_import_2026','students-rising-above'),
  ('Able Works','nonprofit','prospect',null,null,'able.is','partner_import_2026','able-works'),
  ('Alpha Public Schools','school','prospect',null,null,'alphapublicschools.org','partner_import_2026','alpha-public-schools'),
  ('Alternatives in Action','nonprofit','prospect','Oakland',null,'alternativesinaction.org','partner_import_2026','alternatives-in-action'),
  ('Arise High School','school','prospect','Oakland',null,'arisehighschool.org','partner_import_2026','arise-high-school'),
  ('Aspire Public Schools','school','prospect',null,null,'aspirepublicschools.org','partner_import_2026','aspire-public-schools'),
  ('Avid (Menlo Atherton, Sequoia, Woodside)','nonprofit','prospect',null,null,'avid.org','partner_import_2026','avid-menlo-atherton-sequoia-woodside'),
  ('Beyond Emancipation','nonprofit','prospect','Oakland',null,'beyondemancipation.org','partner_import_2026','beyond-emancipation'),
  ('Black Teacher Network','nonprofit','prospect',null,null,null,'partner_import_2026','black-teacher-network'),
  ('Calistoga High School','school','prospect',null,null,'calistogajusd.org','partner_import_2026','calistoga-high-school'),
  ('Civicorps','nonprofit','prospect','Oakland',null,'cvcorps.org','partner_import_2026','civicorps'),
  ('Dream Catchers','nonprofit','prospect','EPA',null,'dreamcatchersyouth.org','partner_import_2026','dream-catchers'),
  ('East Oakland Youth Development Center','nonprofit','prospect',null,null,'eoydc.org','partner_import_2026','east-oakland-youth-development-center'),
  ('Envision','nonprofit','prospect',null,null,'envisionacademy.org','partner_import_2026','envision'),
  ('First Place for Youth','nonprofit','prospect',null,null,'firstplaceforyouth.org','partner_import_2026','first-place-for-youth'),
  ('Foundation for College Education','nonprofit','prospect',null,null,'collegefoundation.org','partner_import_2026','foundation-for-college-education'),
  ('Gateway High School','school','prospect',null,null,'gatewayhigh.org','partner_import_2026','gateway-high-school'),
  ('Girl Ventures','nonprofit','prospect',null,null,'girlventure.org','partner_import_2026','girl-ventures'),
  ('Hayward High School','school','prospect','Hayward',null,'husd.k12.ca.us','partner_import_2026','hayward-high-school'),
  ('Jobs for American Graduates (JAG)','nonprofit','prospect',null,null,'jag.org','partner_import_2026','jobs-for-american-graduates-jag'),
  ('McClymonds High School','school','prospect','Oakland','CA',null,'partner_import_2026','mcclymonds-high-school'),
  ('National Association of Manufacturers','nonprofit','prospect',null,null,'nam.org','partner_import_2026','national-association-of-manufacturers'),
  ('Next Generation Atlanta','nonprofit','prospect',null,null,'nextgenatl.org','partner_import_2026','next-generation-atlanta'),
  ('Oakland Kids First','nonprofit','prospect','Oakland',null,'oaklandkidsfirst.org','partner_import_2026','oakland-kids-first'),
  ('Oakland Promise','nonprofit','prospect',null,null,'oaklandpromise.org','partner_import_2026','oakland-promise'),
  ('Opportunity Trust','nonprofit','prospect','St. Loius',null,'theopportunitytrust.org','partner_import_2026','opportunity-trust'),
  ('Oxford Day Academy','school','prospect',null,null,'oxforddayacademy.org','partner_import_2026','oxford-day-academy'),
  ('Riekes Center','nonprofit','prospect',null,null,'riekes.org','partner_import_2026','riekes-center'),
  ('Rooted Schools','school','prospect',null,null,'rootedschool.org','partner_import_2026','rooted-schools'),
  ('San Mateo Library','nonprofit','prospect',null,null,'smcl.org','partner_import_2026','san-mateo-library'),
  ('SF Oasis','nonprofit','prospect',null,null,'sfoasis.org','partner_import_2026','sf-oasis'),
  ('Silicon Valley Education Foundation','nonprofit','prospect',null,null,null,'partner_import_2026','silicon-valley-education-foundation'),
  ('Silicon Valley Urban Debate Leage','nonprofit','prospect',null,null,'svudl.org','partner_import_2026','silicon-valley-urban-debate-leage'),
  ('Street Code','nonprofit','prospect',null,null,'streetcode.org','partner_import_2026','street-code'),
  ('SVEF','nonprofit','prospect',null,null,'svefoundation.org','partner_import_2026','svef'),
  ('Tech Exposure & Access Through Mentoring (TEAM)','nonprofit','prospect','Oakland',null,'wearteaminc.org','partner_import_2026','tech-exposure-access-through-mentoring-team'),
  ('uAspire','nonprofit','prospect','Oakland',null,'uaspire.org','partner_import_2026','uaspire'),
  ('Woodside High School','school','prospect','Woodside','CA',null,'partner_import_2026','woodside-high-school'),
  ('XQ America - Latitude High School','school','prospect','Oakland',null,'xqsuperschool.org','partner_import_2026','xq-america-latitude-high-school'),
  ('YMCA of Silicon Valley','nonprofit','prospect',null,null,'ymcasv.org','partner_import_2026','ymca-of-silicon-valley'),
  ('Youth Guidence','nonprofit','prospect','Boston',null,'youth-guidance.org','partner_import_2026','youth-guidence'),
  ('Youth Organizing Council (YOC)','nonprofit','prospect','Oakland',null,'oaklandkidsfirst.org','partner_import_2026','youth-organizing-council-yoc'),
  ('Youth Together','nonprofit','prospect','Oakland',null,'youthtogether.net','partner_import_2026','youth-together'),
  ('Youthbeat','nonprofit','prospect','Oakland',null,'youthbeat.org','partner_import_2026','youthbeat')
on conflict (external_source, external_id) where external_id is not null do update set
  kind = excluded.kind, status = excluded.status, city = coalesce(excluded.city, partners.city),
  region = coalesce(excluded.region, partners.region), domain = coalesce(excluded.domain, partners.domain);

-- Contacts (linked by partner external_id).
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Frank', 'Delgado', 'fdelgado@aimhigh.org', 'partner_import_2026', 'aim-high--fdelgado-aimhigh-org' from partners p where p.external_source='partner_import_2026' and p.external_id='aim-high' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Benjie', 'Achtenberg', 'bachtenberg@aimhigh.org', 'partner_import_2026', 'aim-high--bachtenberg-aimhigh-org' from partners p where p.external_source='partner_import_2026' and p.external_id='aim-high' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Jennifer', 'Veveiros', 'jveveiros@aimhigh.org', 'partner_import_2026', 'aim-high--jveveiros-aimhigh-org' from partners p where p.external_source='partner_import_2026' and p.external_id='aim-high' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Stephanie', 'Hipps', 'shipps@alamedaunified.org', 'partner_import_2026', 'alameda-unified--shipps-alamedaunified-org' from partners p where p.external_source='partner_import_2026' and p.external_id='alameda-unified' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Eduardo', 'Arellanes Loeze', 'eloeza@breakthroughsv.org', 'partner_import_2026', 'breakthrough--eloeza-breakthroughsv-org' from partners p where p.external_source='partner_import_2026' and p.external_id='breakthrough' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Thao', 'Nguyen', 'thao.nguyen@breakthroughsv.org', 'partner_import_2026', 'breakthrough--thao-nguyen-breakthroughsv-org' from partners p where p.external_source='partner_import_2026' and p.external_id='breakthrough' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Nkia', 'Richardson', 'nkia@casaofsanmateo.org', 'partner_import_2026', 'casa--nkia-casaofsanmateo-org' from partners p where p.external_source='partner_import_2026' and p.external_id='casa' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Joseph', 'Blasher', 'joseph.blasher@ousd.org', 'partner_import_2026', 'castlemont-high-school--joseph-blasher-ousd-org' from partners p where p.external_source='partner_import_2026' and p.external_id='castlemont-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Sarah', 'Fortner', 'sarah@caterpillarministries.org', 'partner_import_2026', 'caterpillar-ministries-nc--sarah-caterpillarministries-org' from partners p where p.external_source='partner_import_2026' and p.external_id='caterpillar-ministries-nc' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Amika', 'Guillaume', null, 'partner_import_2026', 'collegetrack--amika-guillaume' from partners p where p.external_source='partner_import_2026' and p.external_id='collegetrack' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Hashim', 'Muhammad', 'hashim@digitalnest.org', 'partner_import_2026', 'digital-nest--hashim-digitalnest-org' from partners p where p.external_source='partner_import_2026' and p.external_id='digital-nest' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Beth', 'Kukla', 'beth@digitalnest.org', 'partner_import_2026', 'digital-nest--beth-digitalnest-org' from partners p where p.external_source='partner_import_2026' and p.external_id='digital-nest' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Dr. Sabrina', 'Silverman-Fernandez', 'ssilverman@seq.org', 'partner_import_2026', 'east-palo-alto-academy--ssilverman-seq-org' from partners p where p.external_source='partner_import_2026' and p.external_id='east-palo-alto-academy' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Chris', 'Bischof', 'chrisb@eastside.org', 'partner_import_2026', 'eastside-college-prep--chrisb-eastside-org' from partners p where p.external_source='partner_import_2026' and p.external_id='eastside-college-prep' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Kevin', 'Cauich', 'kcauich@enterpriseforyouth.org', 'partner_import_2026', 'enterprise-for-youth--kcauich-enterpriseforyouth-org' from partners p where p.external_source='partner_import_2026' and p.external_id='enterprise-for-youth' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Carlo', 'Solis', 'csolis@enterpriseforyouth.org', 'partner_import_2026', 'enterprise-for-youth--csolis-enterpriseforyouth-org' from partners p where p.external_source='partner_import_2026' and p.external_id='enterprise-for-youth' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Sharon', 'Washington-Barnes', 'sharon@eoydc.org', 'partner_import_2026', 'eoydc--sharon-eoydc-org' from partners p where p.external_source='partner_import_2026' and p.external_id='eoydc' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Landon', 'Hill', 'landon@eoydc.org', 'partner_import_2026', 'eoydc--landon-eoydc-org' from partners p where p.external_source='partner_import_2026' and p.external_id='eoydc' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Selena', 'Wilson', 'selena@eoydc.org', 'partner_import_2026', 'eoydc--selena-eoydc-org' from partners p where p.external_source='partner_import_2026' and p.external_id='eoydc' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Ashanti', 'Branch', 'everforwardclub@gmail.com', 'partner_import_2026', 'ever-forward-club--everforwardclub-gmail-com' from partners p where p.external_source='partner_import_2026' and p.external_id='ever-forward-club' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Melissa', 'Poling', 'melissa@flyprogram.org', 'partner_import_2026', 'fly--melissa-flyprogram-org' from partners p where p.external_source='partner_import_2026' and p.external_id='fly' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Tammy', 'Gaiter', 'tgaiter@friendsofthechildren.org', 'partner_import_2026', 'friends-of-the-children--tgaiter-friendsofthechildren-org' from partners p where p.external_source='partner_import_2026' and p.external_id='friends-of-the-children' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Carmi', 'Brown', 'cbrown@friendsofthechildren.org', 'partner_import_2026', 'friends-of-the-children--cbrown-friendsofthechildren-org' from partners p where p.external_source='partner_import_2026' and p.external_id='friends-of-the-children' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Dr. Andrae', 'Brown', 'abrown@friendsofthechildren.org', 'partner_import_2026', 'friends-of-the-children--abrown-friendsofthechildren-org' from partners p where p.external_source='partner_import_2026' and p.external_id='friends-of-the-children' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Dr. Susan', 'Walsh', 'swalsh@friendsofthechildren.org', 'partner_import_2026', 'friends-of-the-children--swalsh-friendsofthechildren-org' from partners p where p.external_source='partner_import_2026' and p.external_id='friends-of-the-children' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Samia', 'Zuber', 'samia@hackthehood.org', 'partner_import_2026', 'hack-the-hood--samia-hackthehood-org' from partners p where p.external_source='partner_import_2026' and p.external_id='hack-the-hood' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Diana', 'Levy', 'dlevy@husd.k12.ca.us', 'partner_import_2026', 'hayward-unified--dlevy-husd-k12-ca-us' from partners p where p.external_source='partner_import_2026' and p.external_id='hayward-unified' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Jabari', 'Alii', 'jabari@hiddengeniusproject.org', 'partner_import_2026', 'hidden-genius--jabari-hiddengeniusproject-org' from partners p where p.external_source='partner_import_2026' and p.external_id='hidden-genius' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Janay', 'Osbourne', 'janay@hiddengeniusproject.org', 'partner_import_2026', 'hidden-genius--janay-hiddengeniusproject-org' from partners p where p.external_source='partner_import_2026' and p.external_id='hidden-genius' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Serita', 'Cox', 'serita@ifoster.org', 'partner_import_2026', 'ifoster--serita-ifoster-org' from partners p where p.external_source='partner_import_2026' and p.external_id='ifoster' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Dr. Erica', 'Conners', 'erica@improveyourtomorrow.org', 'partner_import_2026', 'improve-your-tomorrow--erica-improveyourtomorrow-org' from partners p where p.external_source='partner_import_2026' and p.external_id='improve-your-tomorrow' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Michael', 'Lynch', 'michael@improveyourtomorrow.org', 'partner_import_2026', 'improve-your-tomorrow--michael-improveyourtomorrow-org' from partners p where p.external_source='partner_import_2026' and p.external_id='improve-your-tomorrow' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Menne', 'Hall', 'menne@improveyourtomorrow.org', 'partner_import_2026', 'improve-your-tomorrow--menne-improveyourtomorrow-org' from partners p where p.external_source='partner_import_2026' and p.external_id='improve-your-tomorrow' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Jenny', 'Rizzo', 'jenny@jklivin.net', 'partner_import_2026', 'just-keep-livin--jenny-jklivin-net' from partners p where p.external_source='partner_import_2026' and p.external_id='just-keep-livin' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Shannon', 'Rotenberg', 'shannon@jklivin.net', 'partner_import_2026', 'just-keep-livin--shannon-jklivin-net' from partners p where p.external_source='partner_import_2026' and p.external_id='just-keep-livin' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Leon', 'Clayborne', 'leon@jklivin.net', 'partner_import_2026', 'just-keep-livin--leon-jklivin-net' from partners p where p.external_source='partner_import_2026' and p.external_id='just-keep-livin' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Karin', 'Huber-Levy', 'k.huberlevy@sbcglobal.net', 'partner_import_2026', 'juvenile-hall--k-huberlevy-sbcglobal-net' from partners p where p.external_source='partner_import_2026' and p.external_id='juvenile-hall' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Chris', 'Chatmon', 'chris@kingmakersofoakland.org', 'partner_import_2026', 'kingmakers--chris-kingmakersofoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='kingmakers' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Kahlil', 'Chatmon', 'kahlil@kingmakersofoakland.org', 'partner_import_2026', 'kingmakers--kahlil-kingmakersofoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='kingmakers' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Adrian', 'Henderson', 'adrian@kingmakersofoakland.org', 'partner_import_2026', 'kingmakers--adrian-kingmakersofoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='kingmakers' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'David "T"', 'Taufoou', 'dtaufoou@lemofoundation.org', 'partner_import_2026', 'lemo--dtaufoou-lemofoundation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='lemo' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Ali', 'Magner', 'amagner@lemofoundation.org', 'partner_import_2026', 'lemo--amagner-lemofoundation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='lemo' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Heather', 'Starnes-Logwood', 'heather@liveinpeace.org', 'partner_import_2026', 'live-in-peace--heather-liveinpeace-org' from partners p where p.external_source='partner_import_2026' and p.external_id='live-in-peace' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Sonja', 'Gee', 'sgee@mamhouston.org', 'partner_import_2026', 'mam-houston--sgee-mamhouston-org' from partners p where p.external_source='partner_import_2026' and p.external_id='mam-houston' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Shantell', 'Legaspi', 'slegaspi@mamhouston.org', 'partner_import_2026', 'mam-houston--slegaspi-mamhouston-org' from partners p where p.external_source='partner_import_2026' and p.external_id='mam-houston' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Symone', 'Morales', 'symone.morales@onegoalgraduation.org', 'partner_import_2026', 'onegoal--symone-morales-onegoalgraduation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='onegoal' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Melissa', 'Connelly', 'melissa.connelly@onegoalgraduation.org', 'partner_import_2026', 'onegoal--melissa-connelly-onegoalgraduation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='onegoal' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Angela', 'Glymph', 'angela@peerhealthexchange.org', 'partner_import_2026', 'peer-heatlh-exchange--angela-peerhealthexchange-org' from partners p where p.external_source='partner_import_2026' and p.external_id='peer-heatlh-exchange' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Devon', 'Espinoza', 'despinoza@peerhealthexchange.org', 'partner_import_2026', 'peer-heatlh-exchange--despinoza-peerhealthexchange-org' from partners p where p.external_source='partner_import_2026' and p.external_id='peer-heatlh-exchange' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Rene', 'Jimenez', 'rene@peninsulabridge.org', 'partner_import_2026', 'peninsula-bridge--rene-peninsulabridge-org' from partners p where p.external_source='partner_import_2026' and p.external_id='peninsula-bridge' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Kristen', 'Reese', 'kristen@peninsulabridge.org', 'partner_import_2026', 'peninsula-bridge--kristen-peninsulabridge-org' from partners p where p.external_source='partner_import_2026' and p.external_id='peninsula-bridge' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Matt', 'Be', 'matt.bell@pivotalnow.org', 'partner_import_2026', 'pivotalnow--matt-bell-pivotalnow-org' from partners p where p.external_source='partner_import_2026' and p.external_id='pivotalnow' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Jacqueline', 'Naranjo', 'jnaranjo@seq.org', 'partner_import_2026', 'redwood-city-high-school--jnaranjo-seq-org' from partners p where p.external_source='partner_import_2026' and p.external_id='redwood-city-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Komoia', 'Johnson', 'komoia@rjoyoakland.org', 'partner_import_2026', 'rjoy--komoia-rjoyoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='rjoy' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Trevor', 'Thomas', 'tthomas@studentsrisingabove.org', 'partner_import_2026', 'students-rising-above--tthomas-studentsrisingabove-org' from partners p where p.external_source='partner_import_2026' and p.external_id='students-rising-above' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'William', 'Mock', 'wmock@studentsrisingabove.org', 'partner_import_2026', 'students-rising-above--wmock-studentsrisingabove-org' from partners p where p.external_source='partner_import_2026' and p.external_id='students-rising-above' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'John', 'Liotti', 'john@able.is', 'partner_import_2026', 'able-works--john-able-is' from partners p where p.external_source='partner_import_2026' and p.external_id='able-works' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Shara', 'Hedge', 'shegde@alphapublicschools.org', 'partner_import_2026', 'alpha-public-schools--shegde-alphapublicschools-org' from partners p where p.external_source='partner_import_2026' and p.external_id='alpha-public-schools' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Dr. Daniel', 'Zarazua', 'dzarazua@alternativesinaction.org', 'partner_import_2026', 'alternatives-in-action--dzarazua-alternativesinaction-org' from partners p where p.external_source='partner_import_2026' and p.external_id='alternatives-in-action' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Nidia', 'Burgos', 'nburgos@alternativesinaction.org', 'partner_import_2026', 'alternatives-in-action--nburgos-alternativesinaction-org' from partners p where p.external_source='partner_import_2026' and p.external_id='alternatives-in-action' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Asia', 'Laigo', 'alaigo@alternativesinaction.org', 'partner_import_2026', 'alternatives-in-action--alaigo-alternativesinaction-org' from partners p where p.external_source='partner_import_2026' and p.external_id='alternatives-in-action' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Carmen', 'Rivera', 'crivera@alternativesinaction.org', 'partner_import_2026', 'alternatives-in-action--crivera-alternativesinaction-org' from partners p where p.external_source='partner_import_2026' and p.external_id='alternatives-in-action' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Jessica', 'Hernandez', 'jhernandez@alternativesinaction.org', 'partner_import_2026', 'alternatives-in-action--jhernandez-alternativesinaction-org' from partners p where p.external_source='partner_import_2026' and p.external_id='alternatives-in-action' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Karla', 'Gandiaga', 'karla@arisehighschool.org', 'partner_import_2026', 'arise-high-school--karla-arisehighschool-org' from partners p where p.external_source='partner_import_2026' and p.external_id='arise-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Arianna', 'Caplan', 'arianna@arisehighschool.org', 'partner_import_2026', 'arise-high-school--arianna-arisehighschool-org' from partners p where p.external_source='partner_import_2026' and p.external_id='arise-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Trevor', 'Gardner', 'trevor@arisehighschool.org', 'partner_import_2026', 'arise-high-school--trevor-arisehighschool-org' from partners p where p.external_source='partner_import_2026' and p.external_id='arise-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Gaby', 'Sanchez', 'gaby@arisehighschool.org', 'partner_import_2026', 'arise-high-school--gaby-arisehighschool-org' from partners p where p.external_source='partner_import_2026' and p.external_id='arise-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'John', 'Warren', 'john@arisehighschool.org', 'partner_import_2026', 'arise-high-school--john-arisehighschool-org' from partners p where p.external_source='partner_import_2026' and p.external_id='arise-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Mala', 'Batra', 'mala.batra@aspirepublicschools.org', 'partner_import_2026', 'aspire-public-schools--mala-batra-aspirepublicschools-org' from partners p where p.external_source='partner_import_2026' and p.external_id='aspire-public-schools' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Y''Desha', 'Alsup', 'yalsup@avid.org', 'partner_import_2026', 'avid-menlo-atherton-sequoia-woodside--yalsup-avid-org' from partners p where p.external_source='partner_import_2026' and p.external_id='avid-menlo-atherton-sequoia-woodside' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Sonia', 'Beri', 'sberi@beyondemancipation.org', 'partner_import_2026', 'beyond-emancipation--sberi-beyondemancipation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='beyond-emancipation' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Roosevelt', 'Callahan', 'rcallahan@beyondemancipation.org', 'partner_import_2026', 'beyond-emancipation--rcallahan-beyondemancipation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='beyond-emancipation' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Jenni', 'Fick', 'jfick@beyondemancipation.org', 'partner_import_2026', 'beyond-emancipation--jfick-beyondemancipation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='beyond-emancipation' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Ebony', 'Hebert', 'ehebert@beyondemancipation.org', 'partner_import_2026', 'beyond-emancipation--ehebert-beyondemancipation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='beyond-emancipation' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Vanetta', 'Johnson', 'vjohnson@beyondemancipation.org', 'partner_import_2026', 'beyond-emancipation--vjohnson-beyondemancipation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='beyond-emancipation' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Julia', 'Lakes', 'jlakes@beyondemancipation.org', 'partner_import_2026', 'beyond-emancipation--jlakes-beyondemancipation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='beyond-emancipation' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Kat', 'Preston', 'kpreston@beyondemancipation.org', 'partner_import_2026', 'beyond-emancipation--kpreston-beyondemancipation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='beyond-emancipation' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Leila', 'Sotto', 'lsotto@beyondemancipation.org', 'partner_import_2026', 'beyond-emancipation--lsotto-beyondemancipation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='beyond-emancipation' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Ari', 'Turrentine', 'aturrentine@beyondemancipation.org', 'partner_import_2026', 'beyond-emancipation--aturrentine-beyondemancipation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='beyond-emancipation' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Rebecca', 'Duran', 'rduran@breakthroughsv.org', 'partner_import_2026', 'breakthrough--rduran-breakthroughsv-org' from partners p where p.external_source='partner_import_2026' and p.external_id='breakthrough' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Carla', 'Surber', 'csurber@calistogajusd.org', 'partner_import_2026', 'calistoga-high-school--csurber-calistogajusd-org' from partners p where p.external_source='partner_import_2026' and p.external_id='calistoga-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Tessa', 'Nicholas', 'info@cvcorps.org', 'partner_import_2026', 'civicorps--info-cvcorps-org' from partners p where p.external_source='partner_import_2026' and p.external_id='civicorps' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Qa''id', 'Aqeel', 'qaid.aqeel@cvcorps.org', 'partner_import_2026', 'civicorps--qaid-aqeel-cvcorps-org' from partners p where p.external_source='partner_import_2026' and p.external_id='civicorps' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Brian', 'Hickey', 'brian.hickey@cvcorps.org', 'partner_import_2026', 'civicorps--brian-hickey-cvcorps-org' from partners p where p.external_source='partner_import_2026' and p.external_id='civicorps' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Fatima', 'Lopez Sandoval', 'fatima@dreamcatchersyouth.org', 'partner_import_2026', 'dream-catchers--fatima-dreamcatchersyouth-org' from partners p where p.external_source='partner_import_2026' and p.external_id='dream-catchers' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Sharon', 'Washington-Barnes', 'sharon@eoydc.org', 'partner_import_2026', 'east-oakland-youth-development-center--sharon-eoydc-org' from partners p where p.external_source='partner_import_2026' and p.external_id='east-oakland-youth-development-center' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Michael', 'Viera', 'mviera@envisionacademy.org', 'partner_import_2026', 'envision--mviera-envisionacademy-org' from partners p where p.external_source='partner_import_2026' and p.external_id='envision' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Emily', 'Jensen', 'ejensen@firstplaceforyouth.org', 'partner_import_2026', 'first-place-for-youth--ejensen-firstplaceforyouth-org' from partners p where p.external_source='partner_import_2026' and p.external_id='first-place-for-youth' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Elizabeth', 'Wells', 'ewells@collegefoundation.org', 'partner_import_2026', 'foundation-for-college-education--ewells-collegefoundation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='foundation-for-college-education' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Stephanie', 'Khaziran', 'skhaziran@gatewayhigh.org', 'partner_import_2026', 'gateway-high-school--skhaziran-gatewayhigh-org' from partners p where p.external_source='partner_import_2026' and p.external_id='gateway-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Xiomara', 'Batin', 'xiomara@girlventures.org', 'partner_import_2026', 'girl-ventures--xiomara-girlventures-org' from partners p where p.external_source='partner_import_2026' and p.external_id='girl-ventures' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Diana', 'Levy', 'dlevy@husd.k12.ca.us', 'partner_import_2026', 'hayward-high-school--dlevy-husd-k12-ca-us' from partners p where p.external_source='partner_import_2026' and p.external_id='hayward-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Karey', 'Webb', 'karey.webb@jag.org', 'partner_import_2026', 'jobs-for-american-graduates-jag--karey-webb-jag-org' from partners p where p.external_source='partner_import_2026' and p.external_id='jobs-for-american-graduates-jag' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Jennifer', 'White', 'jwhite@nam.org', 'partner_import_2026', 'national-association-of-manufacturers--jwhite-nam-org' from partners p where p.external_source='partner_import_2026' and p.external_id='national-association-of-manufacturers' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Phil', 'Olaleye', 'phil@nextgenatl.org', 'partner_import_2026', 'next-generation-atlanta--phil-nextgenatl-org' from partners p where p.external_source='partner_import_2026' and p.external_id='next-generation-atlanta' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Peter', 'Truong', 'peter@kidsfirstoakland.org', 'partner_import_2026', 'oakland-kids-first--peter-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-kids-first' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Domenichi', 'Morris', 'domenichi@kidsfirstoakland.org', 'partner_import_2026', 'oakland-kids-first--domenichi-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-kids-first' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Hadiyah', 'Owens', 'hadiyah@kidsfirstoakland.org', 'partner_import_2026', 'oakland-kids-first--hadiyah-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-kids-first' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Maya', 'Rapier', 'maya@kidsfirstoakland.org', 'partner_import_2026', 'oakland-kids-first--maya-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-kids-first' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Janet', 'Chavez', 'janet@kidsfirstoakland.org', 'partner_import_2026', 'oakland-kids-first--janet-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-kids-first' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Rosario', 'Diaz', 'rosario@kidsfirstoakland.org', 'partner_import_2026', 'oakland-kids-first--rosario-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-kids-first' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Lukas', 'Brekke-Miesner', 'lukas@kidsfirstoakland.org', 'partner_import_2026', 'oakland-kids-first--lukas-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-kids-first' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Sabaa', 'Shoraka', 'sabaa@kidsfirstoakland.org', 'partner_import_2026', 'oakland-kids-first--sabaa-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-kids-first' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Cara', 'Holiday', 'cara@kidsfirstoakland.org', 'partner_import_2026', 'oakland-kids-first--cara-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-kids-first' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Mai', 'Fawaz', 'mai@kidsfirstoakland.org', 'partner_import_2026', 'oakland-kids-first--mai-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-kids-first' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Mo', 'Recorder', 'mo@oaklandpromise.org', 'partner_import_2026', 'oakland-promise--mo-oaklandpromise-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oakland-promise' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Riley', 'Foster', 'rfoster@theopportunitytrust.org', 'partner_import_2026', 'opportunity-trust--rfoster-theopportunitytrust-org' from partners p where p.external_source='partner_import_2026' and p.external_id='opportunity-trust' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Latrice', 'Bennett', 'latrice@oxforddayacademy.org', 'partner_import_2026', 'oxford-day-academy--latrice-oxforddayacademy-org' from partners p where p.external_source='partner_import_2026' and p.external_id='oxford-day-academy' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Summer', 'Camps', 'summer@riekes.org', 'partner_import_2026', 'riekes-center--summer-riekes-org' from partners p where p.external_source='partner_import_2026' and p.external_id='riekes-center' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Talia', 'Livneh', 'tlivneh@rootedschool.org', 'partner_import_2026', 'rooted-schools--tlivneh-rootedschool-org' from partners p where p.external_source='partner_import_2026' and p.external_id='rooted-schools' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Carine', 'Risley', 'risley@smcl.org', 'partner_import_2026', 'san-mateo-library--risley-smcl-org' from partners p where p.external_source='partner_import_2026' and p.external_id='san-mateo-library' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'LaVonda', 'Baldwin', 'lbaldwin@sfoasis.org', 'partner_import_2026', 'sf-oasis--lbaldwin-sfoasis-org' from partners p where p.external_source='partner_import_2026' and p.external_id='sf-oasis' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Kwodwo', 'Moore', 'kmoore@svudl.org', 'partner_import_2026', 'silicon-valley-urban-debate-leage--kmoore-svudl-org' from partners p where p.external_source='partner_import_2026' and p.external_id='silicon-valley-urban-debate-leage' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Tunde', 'Sobomehin', 'tunde@streetcode.org', 'partner_import_2026', 'street-code--tunde-streetcode-org' from partners p where p.external_source='partner_import_2026' and p.external_id='street-code' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Cris', 'Ramirez', 'cris.ramirez@svefoundation.org', 'partner_import_2026', 'svef--cris-ramirez-svefoundation-org' from partners p where p.external_source='partner_import_2026' and p.external_id='svef' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Anwar', 'McQueen', 'anwar@weareteaminc.org', 'partner_import_2026', 'tech-exposure-access-through-mentoring-team--anwar-weareteaminc-org' from partners p where p.external_source='partner_import_2026' and p.external_id='tech-exposure-access-through-mentoring-team' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Janeira', 'Forte', 'janeiraf@uaspire.org', 'partner_import_2026', 'uaspire--janeiraf-uaspire-org' from partners p where p.external_source='partner_import_2026' and p.external_id='uaspire' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Giovanni', 'Germain', 'giovannig@uaspire.org', 'partner_import_2026', 'uaspire--giovannig-uaspire-org' from partners p where p.external_source='partner_import_2026' and p.external_id='uaspire' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Tanya', 'Enriquez', 'tanyae@uaspire.org', 'partner_import_2026', 'uaspire--tanyae-uaspire-org' from partners p where p.external_source='partner_import_2026' and p.external_id='uaspire' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Hallie', 'Hanson', 'hallieh@uaspire.org', 'partner_import_2026', 'uaspire--hallieh-uaspire-org' from partners p where p.external_source='partner_import_2026' and p.external_id='uaspire' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Jaclyn', 'Pinero', 'jaclyn@uaspire.org', 'partner_import_2026', 'uaspire--jaclyn-uaspire-org' from partners p where p.external_source='partner_import_2026' and p.external_id='uaspire' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Christian', 'Martinez', 'christian.martinez@latitudehigh.org', 'partner_import_2026', 'xq-america-latitude-high-school--christian-martinez-latitudehigh-org' from partners p where p.external_source='partner_import_2026' and p.external_id='xq-america-latitude-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'John', 'Bosselman', 'john.bosselman@latitudehigh.org', 'partner_import_2026', 'xq-america-latitude-high-school--john-bosselman-latitudehigh-org' from partners p where p.external_source='partner_import_2026' and p.external_id='xq-america-latitude-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Kibos', 'Buscovich', 'kibos.buscovich@latitudehigh.org', 'partner_import_2026', 'xq-america-latitude-high-school--kibos-buscovich-latitudehigh-org' from partners p where p.external_source='partner_import_2026' and p.external_id='xq-america-latitude-high-school' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Jose', null, 'jose.sanchez@ymcasv.org', 'partner_import_2026', 'ymca-of-silicon-valley--jose-sanchez-ymcasv-org' from partners p where p.external_source='partner_import_2026' and p.external_id='ymca-of-silicon-valley' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'AJ', 'Watson', 'awatson@youth-guidance.org', 'partner_import_2026', 'youth-guidence--awatson-youth-guidance-org' from partners p where p.external_source='partner_import_2026' and p.external_id='youth-guidence' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Domenichi', 'Morris', 'domenichi@kidsfirstoakland.org', 'partner_import_2026', 'youth-organizing-council-yoc--domenichi-kidsfirstoakland-org' from partners p where p.external_source='partner_import_2026' and p.external_id='youth-organizing-council-yoc' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Tony', 'Douangviseth', 'tdouangviseth@youthtogether.net', 'partner_import_2026', 'youth-together--tdouangviseth-youthtogether-net' from partners p where p.external_source='partner_import_2026' and p.external_id='youth-together' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Nancy', 'Phan-Kholes', 'nancy@youthtogether.net', 'partner_import_2026', 'youth-together--nancy-youthtogether-net' from partners p where p.external_source='partner_import_2026' and p.external_id='youth-together' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Stephanie', 'Daniels', 'sdaniels@youthtogether.net', 'partner_import_2026', 'youth-together--sdaniels-youthtogether-net' from partners p where p.external_source='partner_import_2026' and p.external_id='youth-together' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Samantha', 'Silva', 'samantha@youthtogether.net', 'partner_import_2026', 'youth-together--samantha-youthtogether-net' from partners p where p.external_source='partner_import_2026' and p.external_id='youth-together' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Seanna', 'Sou', 'seanna@youthtogether.net', 'partner_import_2026', 'youth-together--seanna-youthtogether-net' from partners p where p.external_source='partner_import_2026' and p.external_id='youth-together' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Xinh', 'Bui', 'xinh@youthtogether.net', 'partner_import_2026', 'youth-together--xinh-youthtogether-net' from partners p where p.external_source='partner_import_2026' and p.external_id='youth-together' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Kathy', 'Thach', 'kathy@youthtogether.net', 'partner_import_2026', 'youth-together--kathy-youthtogether-net' from partners p where p.external_source='partner_import_2026' and p.external_id='youth-together' on conflict (external_source, external_id) where external_id is not null do nothing;
insert into partner_contacts (org_id, partner_id, first_name, last_name, email, external_source, external_id) select p.org_id, p.id, 'Sagesse', 'Graham', 'sagesse@youthbeat.org', 'partner_import_2026', 'youthbeat--sagesse-youthbeat-org' from partners p where p.external_source='partner_import_2026' and p.external_id='youthbeat' on conflict (external_source, external_id) where external_id is not null do nothing;

-- Mark the first-imported contact per org as primary (idempotent).
update partner_contacts c set is_primary = true
from (
  select distinct on (partner_id) id from partner_contacts
  where external_source = 'partner_import_2026'
  order by partner_id, created_at
) f
where c.id = f.id and c.is_primary = false;
